// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BackupDatabase():Promise<string>;

export function CreateCategory(arg1:models.Category):Promise<void>;

export function CreateCustomer(arg1:models.Customer):Promise<void>;

export function CreateProduct(arg1:models.Product):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function DeleteProduct(arg1:string):Promise<void>;

export function GetAllCategories():Promise<Array<models.Category>>;

export function GetAllCustomers():Promise<Array<models.Customer>>;

export function GetAllProducts():Promise<Array<models.Product>>;

export function GetAllSales():Promise<Array<models.Sale>>;

export function ProcessSale(arg1:models.Sale):Promise<void>;

export function RestoreDatabase():Promise<boolean>;

export function UpdateCategory(arg1:models.Category):Promise<void>;

export function UpdateCustomer(arg1:models.Customer):Promise<void>;

export function UpdateProduct(arg1:models.Product):Promise<void>;
