// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDatabase() {
  return window['go']['app']['App']['BackupDatabase']();
}

export function CreateCategory(arg1) {
  return window['go']['app']['App']['CreateCategory'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['app']['App']['CreateCustomer'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['app']['App']['CreateProduct'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['app']['App']['DeleteCategory'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['app']['App']['DeleteCustomer'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['app']['App']['DeleteProduct'](arg1);
}

export function GetAllCategories() {
  return window['go']['app']['App']['GetAllCategories']();
}

export function GetAllCustomers() {
  return window['go']['app']['App']['GetAllCustomers']();
}

export function GetAllProducts() {
  return window['go']['app']['App']['GetAllProducts']();
}

export function GetAllSales() {
  return window['go']['app']['App']['GetAllSales']();
}

export function ProcessSale(arg1) {
  return window['go']['app']['App']['ProcessSale'](arg1);
}

export function RestoreDatabase() {
  return window['go']['app']['App']['RestoreDatabase']();
}

export function UpdateCategory(arg1) {
  return window['go']['app']['App']['UpdateCategory'](arg1);
}

export function UpdateCustomer(arg1) {
  return window['go']['app']['App']['UpdateCustomer'](arg1);
}

export function UpdateProduct(arg1) {
  return window['go']['app']['App']['UpdateProduct'](arg1);
}
